//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace IATClient.XmlPackaging {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IATConfigFile")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="IATConfigFile", IsNullable=false)]
    public partial class ConfigFile {
        
        private string serverURLField;
        
        private int numIATItemsField;
        
        private bool is7BlockField;
        
        private string redirectUponCompleteField;
        
        private int leftResponseASCIIKeyCodeUpperField;
        
        private int rightResponseASCIIKeyCodeUpperField;
        
        private int leftResponseASCIIKeyCodeLowerField;
        
        private int rightResponseASCIIKeyCodeLowerField;
        
        private RandomizationType randomizationTypeField;
        
        private int errorMarkIDField;
        
        private int leftKeyOutlineIDField;
        
        private int rightKeyOutlineIDField;
        
        private bool prefixSelfAlternatingSurveysField;
        
        private IATSurvey[] beforeSurveysField;
        
        private IATSurvey[] afterSurveysField;
        
        private IATLayout layoutField;
        
        private IATEventList eventListField;
        
        private DisplayItemList displayItemsField;
        
        private string nameField;
        
        /// <remarks/>
        public string ServerURL {
            get {
                return this.serverURLField;
            }
            set {
                this.serverURLField = value;
            }
        }
        
        /// <remarks/>
        public int NumIATItems {
            get {
                return this.numIATItemsField;
            }
            set {
                this.numIATItemsField = value;
            }
        }
        
        /// <remarks/>
        public bool Is7Block {
            get {
                return this.is7BlockField;
            }
            set {
                this.is7BlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string RedirectUponComplete {
            get {
                return this.redirectUponCompleteField;
            }
            set {
                this.redirectUponCompleteField = value;
            }
        }
        
        /// <remarks/>
        public int LeftResponseASCIIKeyCodeUpper {
            get {
                return this.leftResponseASCIIKeyCodeUpperField;
            }
            set {
                this.leftResponseASCIIKeyCodeUpperField = value;
            }
        }
        
        /// <remarks/>
        public int RightResponseASCIIKeyCodeUpper {
            get {
                return this.rightResponseASCIIKeyCodeUpperField;
            }
            set {
                this.rightResponseASCIIKeyCodeUpperField = value;
            }
        }
        
        /// <remarks/>
        public int LeftResponseASCIIKeyCodeLower {
            get {
                return this.leftResponseASCIIKeyCodeLowerField;
            }
            set {
                this.leftResponseASCIIKeyCodeLowerField = value;
            }
        }
        
        /// <remarks/>
        public int RightResponseASCIIKeyCodeLower {
            get {
                return this.rightResponseASCIIKeyCodeLowerField;
            }
            set {
                this.rightResponseASCIIKeyCodeLowerField = value;
            }
        }
        
        /// <remarks/>
        public RandomizationType RandomizationType {
            get {
                return this.randomizationTypeField;
            }
            set {
                this.randomizationTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorMarkID {
            get {
                return this.errorMarkIDField;
            }
            set {
                this.errorMarkIDField = value;
            }
        }
        
        /// <remarks/>
        public int LeftKeyOutlineID {
            get {
                return this.leftKeyOutlineIDField;
            }
            set {
                this.leftKeyOutlineIDField = value;
            }
        }
        
        /// <remarks/>
        public int RightKeyOutlineID {
            get {
                return this.rightKeyOutlineIDField;
            }
            set {
                this.rightKeyOutlineIDField = value;
            }
        }
        
        /// <remarks/>
        public bool PrefixSelfAlternatingSurveys {
            get {
                return this.prefixSelfAlternatingSurveysField;
            }
            set {
                this.prefixSelfAlternatingSurveysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BeforeSurveys")]
        public IATSurvey[] BeforeSurveys {
            get {
                return this.beforeSurveysField;
            }
            set {
                this.beforeSurveysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AfterSurveys")]
        public IATSurvey[] AfterSurveys {
            get {
                return this.afterSurveysField;
            }
            set {
                this.afterSurveysField = value;
            }
        }
        
        /// <remarks/>
        public IATLayout Layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
        
        /// <remarks/>
        public IATEventList EventList {
            get {
                return this.eventListField;
            }
            set {
                this.eventListField = value;
            }
        }
        
        /// <remarks/>
        public DisplayItemList DisplayItems {
            get {
                return this.displayItemsField;
            }
            set {
                this.displayItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public enum RandomizationType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        RandomOrder,
        
        /// <remarks/>
        SetNumberOfPresentations,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class IATSurvey {
        
        private string surveyNameField;
        
        private int numItemsField;
        
        private bool isBeforeSurveyField;
        
        private int alternationSetField;
        
        /// <remarks/>
        public string SurveyName {
            get {
                return this.surveyNameField;
            }
            set {
                this.surveyNameField = value;
            }
        }
        
        /// <remarks/>
        public int NumItems {
            get {
                return this.numItemsField;
            }
            set {
                this.numItemsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBeforeSurvey {
            get {
                return this.isBeforeSurveyField;
            }
            set {
                this.isBeforeSurveyField = value;
            }
        }
        
        /// <remarks/>
        public int AlternationSet {
            get {
                return this.alternationSetField;
            }
            set {
                this.alternationSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class IATDisplayItem {
        
        private int idField;
        
        private string filenameField;
        
        private int xField;
        
        private int yField;
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class DisplayItemList {
        
        private IATDisplayItem[] displayItemField;
        
        private int numDisplayItemsField;
        
        private bool numDisplayItemsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DisplayItem")]
        public IATDisplayItem[] DisplayItem {
            get {
                return this.displayItemField;
            }
            set {
                this.displayItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumDisplayItems {
            get {
                return this.numDisplayItemsField;
            }
            set {
                this.numDisplayItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumDisplayItemsSpecified {
            get {
                return this.numDisplayItemsFieldSpecified;
            }
            set {
                this.numDisplayItemsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IATInstructionScreen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyedInstructionScreen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MockItemInstructionScreen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextInstructionScreen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BeginInstructionBlock))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IATItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EndIATBlock))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BeginIATBlock))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public abstract partial class IATEvent {
        
        private IATEventType eventTypeField;
        
        /// <remarks/>
        public IATEventType EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public enum IATEventType {
        
        /// <remarks/>
        BeginIATBlock,
        
        /// <remarks/>
        EndIATBlock,
        
        /// <remarks/>
        IATItem,
        
        /// <remarks/>
        BeginInstructionBlock,
        
        /// <remarks/>
        TextInstructionScreen,
        
        /// <remarks/>
        MockItemInstructionScreen,
        
        /// <remarks/>
        KeyedInstructionScreen,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyedInstructionScreen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MockItemInstructionScreen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextInstructionScreen))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public abstract partial class IATInstructionScreen : IATEvent {
        
        private int continueASCIIKeyCodeField;
        
        private int continueInstructionsDisplayIDField;
        
        /// <remarks/>
        public int ContinueASCIIKeyCode {
            get {
                return this.continueASCIIKeyCodeField;
            }
            set {
                this.continueASCIIKeyCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ContinueInstructionsDisplayID {
            get {
                return this.continueInstructionsDisplayIDField;
            }
            set {
                this.continueInstructionsDisplayIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class KeyedInstructionScreen : IATInstructionScreen {
        
        private int instructionsDisplayIDField;
        
        private int leftResponseDisplayIDField;
        
        private int rightResponseDisplayIDField;
        
        /// <remarks/>
        public int InstructionsDisplayID {
            get {
                return this.instructionsDisplayIDField;
            }
            set {
                this.instructionsDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public int LeftResponseDisplayID {
            get {
                return this.leftResponseDisplayIDField;
            }
            set {
                this.leftResponseDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public int RightResponseDisplayID {
            get {
                return this.rightResponseDisplayIDField;
            }
            set {
                this.rightResponseDisplayIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class MockItemInstructionScreen : IATInstructionScreen {
        
        private int leftResponseDisplayIDField;
        
        private int rightResponseDisplayIDField;
        
        private int stimulusDisplayIDField;
        
        private int instructionsDisplayIDField;
        
        private bool errorMarkIsDisplayedField;
        
        private bool outlineLeftResponseField;
        
        private bool outlineRightResponseField;
        
        /// <remarks/>
        public int LeftResponseDisplayID {
            get {
                return this.leftResponseDisplayIDField;
            }
            set {
                this.leftResponseDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public int RightResponseDisplayID {
            get {
                return this.rightResponseDisplayIDField;
            }
            set {
                this.rightResponseDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public int StimulusDisplayID {
            get {
                return this.stimulusDisplayIDField;
            }
            set {
                this.stimulusDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public int InstructionsDisplayID {
            get {
                return this.instructionsDisplayIDField;
            }
            set {
                this.instructionsDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public bool ErrorMarkIsDisplayed {
            get {
                return this.errorMarkIsDisplayedField;
            }
            set {
                this.errorMarkIsDisplayedField = value;
            }
        }
        
        /// <remarks/>
        public bool OutlineLeftResponse {
            get {
                return this.outlineLeftResponseField;
            }
            set {
                this.outlineLeftResponseField = value;
            }
        }
        
        /// <remarks/>
        public bool OutlineRightResponse {
            get {
                return this.outlineRightResponseField;
            }
            set {
                this.outlineRightResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class TextInstructionScreen : IATInstructionScreen {
        
        private int instructionsDisplayIDField;
        
        /// <remarks/>
        public int InstructionsDisplayID {
            get {
                return this.instructionsDisplayIDField;
            }
            set {
                this.instructionsDisplayIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class BeginInstructionBlock : IATEvent {
        
        private int numInstructionScreensField;
        
        private int alternateWithField;
        
        /// <remarks/>
        public int NumInstructionScreens {
            get {
                return this.numInstructionScreensField;
            }
            set {
                this.numInstructionScreensField = value;
            }
        }
        
        /// <remarks/>
        public int AlternateWith {
            get {
                return this.alternateWithField;
            }
            set {
                this.alternateWithField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class IATItem : IATEvent {
        
        private int itemNumberField;
        
        private int blockNumField;
        
        private bool isPracticeItemField;
        
        private int stimulusDisplayIDField;
        
        private KeyedDir keyedDirField;
        
        /// <remarks/>
        public int ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public int BlockNum {
            get {
                return this.blockNumField;
            }
            set {
                this.blockNumField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPracticeItem {
            get {
                return this.isPracticeItemField;
            }
            set {
                this.isPracticeItemField = value;
            }
        }
        
        /// <remarks/>
        public int StimulusDisplayID {
            get {
                return this.stimulusDisplayIDField;
            }
            set {
                this.stimulusDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public KeyedDir KeyedDir {
            get {
                return this.keyedDirField;
            }
            set {
                this.keyedDirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public enum KeyedDir {
        
        /// <remarks/>
        Left,
        
        /// <remarks/>
        Right,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class EndIATBlock : IATEvent {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class BeginIATBlock : IATEvent {
        
        private int blockNumField;
        
        private int numItemsField;
        
        private bool practiceBlockField;
        
        private int instructionsDisplayIDField;
        
        private int leftResponseDisplayIDField;
        
        private int rightResponseDisplayIDField;
        
        private int numPresentationsField;
        
        private bool numPresentationsFieldSpecified;
        
        private int alternatedWithField;
        
        private bool alternatedWithFieldSpecified;
        
        /// <remarks/>
        public int BlockNum {
            get {
                return this.blockNumField;
            }
            set {
                this.blockNumField = value;
            }
        }
        
        /// <remarks/>
        public int NumItems {
            get {
                return this.numItemsField;
            }
            set {
                this.numItemsField = value;
            }
        }
        
        /// <remarks/>
        public bool PracticeBlock {
            get {
                return this.practiceBlockField;
            }
            set {
                this.practiceBlockField = value;
            }
        }
        
        /// <remarks/>
        public int InstructionsDisplayID {
            get {
                return this.instructionsDisplayIDField;
            }
            set {
                this.instructionsDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public int LeftResponseDisplayID {
            get {
                return this.leftResponseDisplayIDField;
            }
            set {
                this.leftResponseDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        public int RightResponseDisplayID {
            get {
                return this.rightResponseDisplayIDField;
            }
            set {
                this.rightResponseDisplayIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumPresentations {
            get {
                return this.numPresentationsField;
            }
            set {
                this.numPresentationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumPresentationsSpecified {
            get {
                return this.numPresentationsFieldSpecified;
            }
            set {
                this.numPresentationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AlternatedWith {
            get {
                return this.alternatedWithField;
            }
            set {
                this.alternatedWithField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlternatedWithSpecified {
            get {
                return this.alternatedWithFieldSpecified;
            }
            set {
                this.alternatedWithFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class IATEventList {
        
        private IATEvent[] iATEventField;
        
        private int numEventsField;
        
        private bool numEventsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IATEvent")]
        public IATEvent[] IATEvent {
            get {
                return this.iATEventField;
            }
            set {
                this.iATEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumEvents {
            get {
                return this.numEventsField;
            }
            set {
                this.numEventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumEventsSpecified {
            get {
                return this.numEventsFieldSpecified;
            }
            set {
                this.numEventsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IATConfigFile")]
    public partial class IATLayout {
        
        private int interiorWidthField;
        
        private int interiorHeightField;
        
        private int borderWidthField;
        
        private byte[] borderColorRField;
        
        private byte[] borderColorGField;
        
        private byte[] borderColorBField;
        
        private byte[] backColorRField;
        
        private byte[] backColorGField;
        
        private byte[] backColorBField;
        
        private byte[] outlineColorRField;
        
        private byte[] outlineColorGField;
        
        private byte[] outlineColorBField;
        
        /// <remarks/>
        public int InteriorWidth {
            get {
                return this.interiorWidthField;
            }
            set {
                this.interiorWidthField = value;
            }
        }
        
        /// <remarks/>
        public int InteriorHeight {
            get {
                return this.interiorHeightField;
            }
            set {
                this.interiorHeightField = value;
            }
        }
        
        /// <remarks/>
        public int BorderWidth {
            get {
                return this.borderWidthField;
            }
            set {
                this.borderWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] BorderColorR {
            get {
                return this.borderColorRField;
            }
            set {
                this.borderColorRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] BorderColorG {
            get {
                return this.borderColorGField;
            }
            set {
                this.borderColorGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] BorderColorB {
            get {
                return this.borderColorBField;
            }
            set {
                this.borderColorBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] BackColorR {
            get {
                return this.backColorRField;
            }
            set {
                this.backColorRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] BackColorG {
            get {
                return this.backColorGField;
            }
            set {
                this.backColorGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] BackColorB {
            get {
                return this.backColorBField;
            }
            set {
                this.backColorBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] OutlineColorR {
            get {
                return this.outlineColorRField;
            }
            set {
                this.outlineColorRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] OutlineColorG {
            get {
                return this.outlineColorGField;
            }
            set {
                this.outlineColorGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] OutlineColorB {
            get {
                return this.outlineColorBField;
            }
            set {
                this.outlineColorBField = value;
            }
        }
    }
}
